### ISSUE TITLE
Fatel Error :  Config Parameter expected

### ISSUE THREAD

**Issue by aryanpatel** [opauth/facebook#18]
`Error: FacebookStrategy config parameter for "xxxxxxxxxxxxxxx" expected.`
`File: /var/www/surejobz/app/Plugin/Opauth/Vendor/Opauth/lib/Opauth/OpauthStrategy.php`
`Line: 201`

Any idea why I am getting this error?

**Comment by Kalahee** [comment]
I know it is late, but if someone find the same issue and I haven't found this question answered anywhere else.

I have the same issue and I think the confusion is that "xxxxxxxxxxxxxxxx" is supposed to be 'app_id' and 'app_secret' and not actual id and secret values. Opauth is looking for those 'keys' in 'strategy' array and I don't think the actual app id is supposed to be a key in that array. In short, we have changed $expects to actual values when it is meant to be keys it will have to look for in the 'strategy' array.
