### ISSUE TITLE
Latest

### ISSUE THREAD

**Issue by eswoosh** [opauth/facebook#21]
Is this currently working? I don't seem to be able to get it running and see it was last updated 2 years ago? .. So is this the latest branch?

**Comment by Limos** [comment]
A bit late to help eswoosh, I'm sure, but I'll post this, hoping it'll help someone else.  

While I was able to get Facebook Login working, I was only receiving the name and id fields, even though I'd requested others (via the 'scope' => 'public_profile,email' conf parameter), and had authorized them via the FB login popup.

I discovered that the specific field names had to be re-requested during ServerGet().  As such, I made the following changes to FacebookStrategy.php:

```php
private function me($access_token){
   $me = $this->serverGet( 'https://graph.facebook.com/me', 
                array( 'access_token' => $access_token, 
                    'fields' => 'id,name,first_name,middle_name,last_name,age_range,gender,locale,timezone,verified,email'
                ), 
                null, $headers 
         );
// ....
```
The fields values should probably be auto-generated from the config file scope settings (with appropriate defaults - all except 'email'), but I'll leave that with "you".  :-)      If requested, I can probably implement this and submit a patch at some point....

I also added the following into the middle of int_callback()

```php
if (!empty($me->gender)) $this->auth['info']['gender'] = $me->gender;
if (!empty($me->locale)) $this->auth['info']['locale'] = $me->locale;
if (!empty($me->timezone)) $this->auth['info']['timezone'] = $me->timezone;

```

I hope that helps!  
Good luck!

**Comment by kktuax** [comment]
Thanks @Limos, with your changes I'm able to retrieve email info. If it's ok for you I'll made a pull-request

**Comment by pixeline** [comment]
Thank you @Limos it fixes the issue raised by [Facebook's update of 8 July 2015](https://developers.facebook.com/blog/post/2015/07/08/graph-api-v2.4/). Namely, it says: 
> Fewer default fields for faster performance: To help improve performance on mobile network connections, we've reduced the number of fields that the API returns by default. You should now use the ?fields=field1,field2 syntax to declare all the fields you want the API to return.'

A codebase update is definitely needed as this is about to make a lot of apps dysfunctional...
