### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by coccoinomane** [opauth/facebook#41]
Hello,

I am sorry to be the one asking it, but... is this strategy still working? Last update was 3 years ago.

Thank you,
Guido

**Comment by sokolnikov911** [comment]
No, it is not. Facebok updated API, and this strategy not working. But I made my own fork https://github.com/sokolnikov911/opauth-facebook-updated, and you can use it.

**Comment by coccoinomane** [comment]
Thank you Sokol!

Will try your fork very soon 😊

Guido

**Comment by jgreth** [comment]
Hey, thanks! Would ask the same, 'cause facebook tells me: 

[MyApp] currently has access to Graph API v2.1 which will reach the end of its 2-year lifetime on 30 October, 2016. To ensure a smooth transition, please migrate all calls to Graph API v2.2 or higher.

**Comment by uzyn** [comment]
Opauth is not actively maintained at this point in time and is seeking maintainers. 
https://github.com/opauth/opauth/issues/118

**Comment by leogermani** [comment]
If you are looking for an updated version of this strategy, here is one:

https://github.com/LibreCoopUruguay/facebook

**Comment by YuzuruS** [comment]
The response from facebook has changed.
If you are looking for an updated version of this strategy, here is one:
https://github.com/schoolwith/facebook

```
	"require": {
		"schoolwith/opauth-facebook": "*"
	},
```

**Comment by uzyn** [comment]
Would anyone of you willing to join Opauth as a core maintainer so that we can close/merge all these?  Please let me know.

opauth/opauth#118

**Comment by YuzuruS** [comment]
I can take over, maintain and update opauth/facebook :)

**Comment by uzyn** [comment]
Awesome @YuzuruS 
Will you also be able to take on Opauth and other official Opauth strategies too?

**Comment by YuzuruS** [comment]
@uzyn thx :)

**Comment by uzyn** [comment]
@YuzuruS Added you as maintainers for all Opauth repositories. 
Thanks!

**Comment by WanWizard** [comment]
Great to see it's being picked again!

**Comment by davidguerrer0** [comment]
Hi, I managed to use the Facebook strategy from 

https://github.com/LibreCoopUruguay/facebook

changing:

parse_str($response, $results);

to

$results=json_decode($response, true);

**Comment by LABCAT** [comment]
So is anyone actually maintaining this repo? 

I see discussion saying someone has taken over but this repo still has issues. 

Can create a pull request but no point if no one will accept it.

**Comment by uzyn** [comment]
I believe @YuzuruS is still maintaining it.

**Comment by YuzuruS** [comment]
I am maintaining it.
In the near future, I close most PRs and merge useful PRs.
