### ISSUE TITLE
Error keys for Error-Callback wrong

### ISSUE THREAD

**Issue by franz-josef-kaiser** [opauth/facebook#44]
The `FacebookStrategy::int_callback()` method fails when there is an error as the [response keys](https://github.com/opauth/facebook/blob/9655f13aa912bf01489c2b3c6888237a8ab9f583/FacebookStrategy.php#L108-L109) are still at the old API. This concerns `v0.3` of this package. PR ahead.

**Comment by YuzuruS** [comment]
@franz-josef-kaiser Thank you!
