### ISSUE TITLE
Facebook folder is ignored by git

### ISSUE THREAD

**Issue by lorimay21** [opauth/facebook#51]
Hello...

I have encountered this problem while using Opauth Facebook.

I cloned this repository into the Strategy folder just like what is instructed in README file.

However, the Facebook folder is seemed to be ignored by git.
I was not able to push it into my project.
I tried checking gitignore files, but it is not included in gitignore.

Can anyone help me regarding this issue? Thank you so much in advance!

**Comment by YuzuruS** [comment]
@lorimay21 
Hi!

1. 
Please check your global gitignore if it is not included in your project gitignore.

2.
If it is possible, could you use composer?
In modan PHP, use composer when installing libraries.

**Comment by lorimay21** [comment]
Hello @YuzuruS !
Thank you so much for replying!

I have already found the solution. It turned out I cloned this repository into my Strategy folder which is also a repository. My mistake! I used git submodule as solution. I will close this issue 😊
