### ISSUE TITLE
New tag/release to be consumed via Composer/Packagist

### ISSUE THREAD

**Issue by henriquemattos** [opauth/facebook#58]
We need a new tag/release to be available in Packagist and be consumed via Composer. Currently version 0.4.4 is from March 2020, and last week new and relevant changes have been introduced to `master`.

Packagist: https://packagist.org/packages/opauth/facebook

**Comment by Bobbybouthot** [comment]
Excellent

**Comment by henriquemattos** [comment]
Hi, @YuzuruS, do you think you can support us here?

**Comment by gimler** [comment]
@uzyn @YuzuruS can some of you create a new tag please?

**Comment by YuzuruS** [comment]
Sorry for the late reply.
We have released a new tag (0.4.5).
Thank you for your cooperation.
